[package]
name = "dof"
description = "Maintain dotfiles from a Git repository"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "dof"
path = "src/main.rs"

[dependencies]
aws-lc-rs.workspace = true
anyhow.workspace = true
clap.workspace = true
gix.workspace = true
jiff.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
tempfile.workspace = true
